#!/usr/bin/env python3

from argparse import ArgumentParser
import os
import subprocess
import socket
import json
import functools

conf_dir=os.path.expanduser('~/.config/aptsandbox/apps')
if not os.path.isdir(conf_dir):
    exit(0)
app_data={}
apps=os.listdir(conf_dir)
for app_file in apps:
    if app_file.endswith('.json'):
        f=open(os.path.join(conf_dir,app_file),'r')
        json_content=json.load(f)
        f.close()
        displayname=json_content.get('name',app_file[:-5])
        values=[app_file[:-5],displayname]
        app_data[app_file[:-5]]=values 
while True:
    cmd=input().strip()
    elements=cmd.split(' ')
    if elements[0]=='exit':
        break
    if elements[0]=='list':
        match_value=""
        for x in elements[1:]:
            if "match=" in x:
                match_value=x.split('=',1)[1]
        for app_id,info in app_data.items():
            if functools.reduce(lambda p,x: p or (match_value in x), info,False):
                print(*info,sep=",")
            